#!/usr/bin/env python3
"""
Parser validation script for log_aggregator.py

Validates JSON, text, and nginx parsers against hand-written fixture data.
Fixtures are independent — NOT generated by the parser code under test —
to avoid the false-pass problem where parser-generated test data
hides regressions.

Usage:
    python3 validate_parsers.py          # runs all fixture checks
    python3 validate_parsers.py --json   # JSON fixtures only
    python3 validate_parsers.py --text   # text fixtures only
    python3 validate_parsers.py --nginx  # nginx fixtures only
    python3 validate_parsers.py --malformed  # malformed/unsupported line checks only
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

# Add parent directory to path so we can import log_aggregator
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from log_aggregator import JSONLogParser, TextLogParser, NginxLogParser


FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures"

# ---------------------------------------------------------------------------
# Helper: check nested field value in a dict using dotted paths
# ---------------------------------------------------------------------------

def get_field(entry: dict, field_path: str):
    """Get a field value, supporting dotted paths like 'fields.status'."""
    parts = field_path.split(".")
    value = entry
    for part in parts:
        if not isinstance(value, dict):
            return None
        value = value.get(part)
    return value


# ---------------------------------------------------------------------------
# Expected parse results
# Each entry is a dict where values are either exact values or callable
# predicates.  Field paths support dotted notation.
# ---------------------------------------------------------------------------

EXPECTED_JSON = [
    # {"timestamp":"2026-06-19T08:15:30Z","level":"INFO","service":"api-gateway",...}
    {"timestamp": "2026-06-19T08:15:30Z", "level": "INFO", "service": "api-gateway",
     "message": "Request received: GET /v1/users", "format": "json"},
    # ERROR
    {"timestamp": "2026-06-19T08:15:31Z", "level": "ERROR", "service": "auth-service",
     "message": "Authentication failed: invalid token", "format": "json"},
    # WARN
    {"timestamp": "2026-06-19T08:16:00Z", "level": "WARN", "service": "payment-worker",
     "message": "Retry attempt 2/3 for transaction tx-456", "format": "json"},
    # DEBUG
    {"timestamp": "2026-06-19T08:17:45Z", "level": "DEBUG", "service": "db-pool",
     "message": "Connection pool stats: active=12 idle=5 waiting=0", "format": "json"},
    # Uses "time","severity","logger","msg" → maps to timestamp/level/service/message
    {"timestamp": "2026-06-19T09:00:00Z", "level": "CRITICAL", "service": "order-service",
     "message": "Out of memory in order processing pipeline", "format": "json"},
    # Uses @timestamp / lvl / app / event
    {"timestamp": "2026-06-19T10:30:00Z", "level": "ERROR", "service": "notification-svc",
     "message": "Failed to send push notification to device: timeout", "format": "json"},
    # INFO scheduler
    {"timestamp": "2026-06-20T00:00:00Z", "level": "INFO", "service": "scheduler",
     "message": "Daily cleanup job started", "format": "json"},
]

EXPECTED_TEXT = [
    # Timestamps should be parsed as epoch ints, service from [bracket]
    {"level": "info", "service": lambda s: s is not None, "format": "text"},
    {"level": "error", "service": lambda s: s is not None, "format": "text"},
    {"level": "warn", "service": lambda s: s is not None, "format": "text"},
    {"level": "debug", "service": lambda s: s is not None, "format": "text"},
    # Note: CRITICAL/FATAL map to 'error' level in the parser's LEVEL_PATTERNS
    {"level": "error", "service": lambda s: s is not None, "format": "text"},
    {"level": "info", "service": lambda s: s is not None, "format": "text"},
]

EXPECTED_NGINX = [
    {"level": "info", "service": "nginx", "fields.status": 200, "format": "nginx",
     "fields.remote_addr": "192.168.1.1"},
    {"level": "warn", "service": "nginx", "fields.status": 401, "format": "nginx",
     "fields.remote_user": "admin"},
    {"level": "info", "service": "nginx", "fields.status": 200, "format": "nginx",
     "fields.request": "GET /health HTTP/1.1"},
    {"level": "error", "service": "nginx", "fields.status": 500, "format": "nginx"},
    {"level": "info", "service": "nginx", "fields.status": 200, "format": "nginx"},
    {"level": "info", "service": "nginx", "fields.status": 204, "format": "nginx"},
]

# ---------------------------------------------------------------------------
# Malformed / unsupported lines that should NOT crash the parser
# ---------------------------------------------------------------------------

MALFORMED_LINES = [
    # Truly empty
    "",
    # Whitespace only
    "   \t  ",
    # Garbage binary-like content
    "\x00\x01\x02\xff\xfe",
    # Random text that doesn't match any format
    "This is not a log line at all, just some random text for testing.",
    # JSON with wrong type (list instead of dict)
    '[1, 2, 3]',
    # JSON truncated/incomplete
    '{"timestamp": "2026-01-01T00:00:00Z", "level": "INFO"',
    # Nginx line with missing trailing fields
    '192.168.1.1 - - [01/Jan/2026:00:00:00 +0000] "GET / HTTP/1.1" 200',
    # Text line that looks like a timestamp but has no level or service
    "2026-01-01 00:00:00 some random message without level brackets",
]

# ---------------------------------------------------------------------------
# Fixture loader
# ---------------------------------------------------------------------------

def load_fixture(name: str) -> list[str]:
    path = FIXTURE_DIR / name
    if not path.exists():
        print(f"  ✗ Fixture not found: {path}")
        sys.exit(1)
    lines = path.read_text(encoding="utf-8").splitlines()
    return [l for l in lines if l.strip() and not l.strip().startswith("#")]


def check_field(entry: dict, field_path: str, expected) -> tuple[bool, str]:
    """Check a field. Returns (passed, error_message)."""
    actual = get_field(entry, field_path)

    if callable(expected):
        ok = expected(actual)
        if ok:
            return True, ""
        return False, f"{field_path}: predicate failed, got {actual!r}"

    if actual == expected:
        return True, ""

    return False, f"{field_path}: expected {expected!r}, got {actual!r}"


def validate_parser(parser, fixture_name: str, expectations: list[dict],
                    label: str) -> tuple[int, int]:
    lines = load_fixture(fixture_name)
    passed = 0
    failed = 0

    print(f"\n  {label} ({len(lines)} lines)")

    for i, line in enumerate(lines):
        entry = parser.parse(line)
        if entry is None:
            print(f"    [{i+1}] ✗ parser returned None")
            failed += 1
            continue

        exp = expectations[i] if i < len(expectations) else {}
        errors = []

        for field, expected_value in exp.items():
            ok, err = check_field(entry, field, expected_value)
            if not ok:
                errors.append(err)

        if errors:
            print(f"    [{i+1}] ✗ {'; '.join(errors)}")
            failed += 1
        else:
            passed += 1

    return passed, failed


def validate_malformed(parsers: list) -> int:
    """Verify that malformed lines don't crash any parser."""
    print(f"\n  Malformed/unsupported lines ({len(MALFORMED_LINES)} cases)")
    crashes = 0

    for i, line in enumerate(MALFORMED_LINES):
        for parser in parsers:
            try:
                parser.parse(line)
            except Exception as e:
                print(f"    [{i+1}] ✗ {parser.__class__.__name__} crashed: {e}")
                crashes += 1

    if crashes == 0:
        print("    ✓ All malformed lines handled without crashes")
    return crashes


def main():
    ap = argparse.ArgumentParser(description="Validate log parsers against fixtures")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--text", action="store_true")
    ap.add_argument("--nginx", action="store_true")
    ap.add_argument("--malformed", action="store_true")
    args = ap.parse_args()

    any_specific = args.json or args.text or args.nginx or args.malformed
    run_json = args.json or not any_specific
    run_text = args.text or not any_specific
    run_nginx = args.nginx or not any_specific
    run_malformed = args.malformed or not any_specific

    total_passed = 0
    total_failed = 0
    total_crashes = 0

    print("=" * 50)
    print("  Log Parser Validation")
    print("  Fixtures: " + str(FIXTURE_DIR))
    print("=" * 50)

    if run_json:
        p, f = validate_parser(JSONLogParser(), "json_logs.fixture",
                                EXPECTED_JSON, "JSON parser")
        total_passed += p
        total_failed += f

    if run_text:
        p, f = validate_parser(TextLogParser(), "text_logs.fixture",
                                EXPECTED_TEXT, "Text parser")
        total_passed += p
        total_failed += f

    if run_nginx:
        p, f = validate_parser(NginxLogParser(), "nginx_logs.fixture",
                                EXPECTED_NGINX, "Nginx parser")
        total_passed += p
        total_failed += f

    if run_malformed:
        parsers = [JSONLogParser(), TextLogParser(), NginxLogParser()]
        total_crashes = validate_malformed(parsers)

    print()
    print("=" * 50)
    print("  Results: {} passed, {} failed, {} crashes".format(
        total_passed, total_failed, total_crashes))
    print("=" * 50)

    if total_failed > 0 or total_crashes > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
